/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class com_xhiston_diffpatch_DiffPatchUtil */

#ifndef _Included_com_xhiston_diffpatch_DiffPatchUtil
#define _Included_com_xhiston_diffpatch_DiffPatchUtil
#ifdef __cplusplus
extern "C" {
#endif

    int mybspatch(JNIEnv *env, jobject clazz,int argc, char *argv[]);

    int mybsdiff(JNIEnv *env, jobject clazz, int argc,char *argv[]);

    JNIEXPORT jint JNICALL Java_com_xhiston_diffpatch_DiffPatchUtil_patch
      (JNIEnv *, jobject, jstring, jstring, jstring);

    JNIEXPORT jint JNICALL Java_com_xhiston_diffpatch_DiffPatchUtil_diff
      (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
